name: Contract tests' validation and publish

on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Run tests
        run: |
          ./gradlew build
